### PR TITLE
Made mocha-phantomjs an external dependency

### PR DESCRIPTION
**Pull request by fearphage**
Also upgraded `mocha-phantomjs` to version 3.5.2.

### CODE REVIEW

**Comment by fearphage** [comment]
@lepture bump.

**Comment by popomore** [comment]
We don't use it in spm3 now.

**Comment by fearphage** [comment]
"It" is referring to `mocha-phantomjs`?
And spm3 is _____?

**Comment by popomore** [comment]
@fearphage  [spm3](https://github.com/spmjs/spm) now use `mocha-phantomjs` directly

**Pull request merged**
